[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  included_files = ["netlify/functions/lib/.github-token.local.txt"]

[[redirects]]
  from = "/api/user"
  to = "/.netlify/functions/user"
  status = 200

[[redirects]]
  from = "/api/prs"
  to = "/.netlify/functions/prs"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
